# Generated by Django 3.2.6 on 2021-09-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Course_home', '0027_alter_course_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('comment', models.TextField(null=True, verbose_name='کامنت')),
                ('is_agree', models.BooleanField(default=False, verbose_name='تایید میشود/نمیشود')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course_home.course', verbose_name='کامنت کدام دوره ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کامنت کدام کاربر')),
            ],
            options={
                'verbose_name': 'کامنت دوره',
                'verbose_name_plural': 'کامنت های دوره',
            },
        ),
    ]
