# Generated by Django 3.2.6 on 2021-09-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0027_alter_course_create_date'),
        ('course_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecourses',
            name='favorite_courses',
        ),
        migrations.AddField(
            model_name='favoritecourses',
            name='favorite_courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course_home.course', verbose_name='دوره های مورد علاقه'),
        ),
    ]
