# Generated by Django 3.2.6 on 2021-08-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0008_coursesessions'),
        ('Users_Buying_Status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersbuysstatus',
            name='courses',
        ),
        migrations.AddField(
            model_name='usersbuysstatus',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course_home.course', verbose_name='دوره های خریداری شده'),
        ),
    ]
