# Generated by Django 3.2.6 on 2021-09-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_settings', '0002_auto_20210906_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='caption',
            field=models.CharField(max_length=120, null=True, verbose_name='متن زیر تیتر سایت'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='title',
            field=models.CharField(max_length=60, null=True, verbose_name='تبتر سایت'),
        ),
    ]
