# Generated by Django 3.2.6 on 2021-09-02 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_forgot_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_created_token',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد توکن'),
            preserve_default=False,
        ),
    ]
