# Generated by Django 3.2.6 on 2021-09-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_time_created_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=35, verbose_name='توکن فراموشی رمز عبور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_created_token',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد توکن'),
        ),
    ]
