# Generated by Django 3.2.6 on 2021-09-03 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_time_created_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_created_token',
            field=models.DateField(blank=True, default=datetime.date(2021, 9, 3), verbose_name='تاریخ ایجاد توکن'),
        ),
    ]
