# Generated by Django 3.2.6 on 2021-09-03 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_user_time_created_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_created_token',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد توکن'),
        ),
    ]
