# Generated by Django 3.2 on 2021-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=120, null=True, verbose_name='سطح')),
            ],
            options={
                'verbose_name': 'سطح',
                'verbose_name_plural': 'سطوح',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='نام دوره')),
                ('level', models.ManyToManyField(null=True, to='Course_home.Level', verbose_name='سطح')),
            ],
        ),
    ]
