# Generated by Django 3.2 on 2021-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ManyToManyField(to='Course_home.Level', verbose_name='سطح'),
        ),
    ]
