# Generated by Django 3.2.6 on 2021-08-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0004_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='امتیاز دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='rate_count',
            field=models.IntegerField(default=0, verbose_name='تعداد امتیاز ثبت شده'),
        ),
    ]
