# Generated by Django 3.2.6 on 2021-08-30 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0005_auto_20210829_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='buyers_count',
            field=models.IntegerField(default=0, null=True, verbose_name='تعداد خرید دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_discount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.IntegerField(null=True, verbose_name='قیمت دوره'),
        ),
    ]
