# Generated by Django 3.2.6 on 2021-08-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0006_auto_20210830_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_course',
            field=models.TextField(null=True, verbose_name='درباره دوره'),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_person',
            field=models.IntegerField(blank=True, null=True, verbose_name='تخفیف تا چه زمانی'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_learn',
            field=models.TextField(null=True, verbose_name='چه چیزی یاد میگیری'),
        ),
    ]
