# Generated by Django 3.2.6 on 2021-08-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0007_auto_20210830_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(max_length=240, null=True, verbose_name='سرتیتر فصل')),
                ('session_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course_home.course', verbose_name='فصل مرتبط به کدام دوره است؟')),
            ],
            options={
                'verbose_name': 'سرفصل دوره',
                'verbose_name_plural': 'سرفصل های دوره',
            },
        ),
    ]
