# Generated by Django 3.2.6 on 2021-08-31 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0008_coursesessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rate_count',
        ),
    ]
