# Generated by Django 3.2.6 on 2021-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0009_auto_20210831_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='final_price',
            field=models.IntegerField(editable=False, null=True, verbose_name='قیمت دوره'),
        ),
    ]
