# Generated by Django 3.2.6 on 2021-08-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0010_course_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='final_price',
            field=models.IntegerField(null=True, verbose_name='قیمت دوره'),
        ),
    ]
