# Generated by Django 3.2.6 on 2021-08-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0013_alter_course_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_duration',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='زمان دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='final_price',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='قیمت دوره'),
        ),
    ]
