# Generated by Django 3.2.6 on 2021-08-31 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Course_home', '0017_auto_20210901_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='buyers',
            field=models.ManyToManyField(blank=True, related_name='_Course_home_course_buyers_+', to=settings.AUTH_USER_MODEL, verbose_name='خریداران دوره'),
        ),
    ]
