# Generated by Django 3.2.6 on 2021-08-31 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Course_home', '0018_alter_course_buyers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='buyers',
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='استاد دوره'),
        ),
    ]
