# Generated by Django 3.2.6 on 2021-09-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0019_auto_20210901_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zip_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فایل منتشر شده '),
        ),
    ]
