# Generated by Django 3.2.6 on 2021-09-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0020_course_zip_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='zip_count',
            new_name='file_count',
        ),
    ]
