# Generated by Django 3.2.6 on 2021-09-06 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0022_course_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد دوره'),
        ),
    ]
