# Generated by Django 3.2.6 on 2021-09-08 18:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0027_alter_course_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about_course',
            field=tinymce.models.HTMLField(null=True, verbose_name='درباره دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='what_you_learn',
            field=tinymce.models.HTMLField(null=True, verbose_name='چه چیزی یاد میگیری'),
        ),
    ]
