# Generated by Django 3.2.6 on 2021-09-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0028_auto_20210908_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(max_length=340, null=True, verbose_name='تگ های دوره را وارد کنید و با , از هم جدا کنید'),
        ),
    ]
