# Generated by Django 3.2.6 on 2021-09-09 09:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0029_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='about_course',
            field=tinymce.models.HTMLField(max_length=150, null=True, verbose_name='درباره دوره'),
        ),
    ]
