# Generated by Django 3.2.6 on 2022-08-31 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Course_home', '0030_alter_course_about_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='buyers_count',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='تعداد خرید دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاریخ ایجاد دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='file_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد فایل منتشر شده '),
        ),
    ]
