# Generated by Django 3.2.6 on 2021-09-06 03:10

import courses_videos.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course_home', '0023_alter_course_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='عنوان ویدیو')),
                ('video', models.FileField(null=True, upload_to=courses_videos.models.video_path, validators=[django.core.validators.FileExtensionValidator(['mkv', 'mp4', 'avi', 'zip'])], verbose_name='ویدیو')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان؟')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='زمان ویدیو')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course_home.course', verbose_name='متعلق به کدام دوره است')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Course_home.coursesessions', verbose_name='سرفصل دوره')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
            },
        ),
    ]
